### ISSUE TITLE
res/public.xml的用途是什么

### ISSUE THREAD

**Issue by chriszhao001** [Efaker/FakerAndroid#11]
兄弟好棒，做的这个很强大。不过我在使用中不知道res/public.xml的用途是什么，而且如果保留这个文件，当我在build.gradle的文件中通过productFlavors配置多编译的时候会发生stableIDs找不到的问题。我在删除了这个文件以后感觉程序运转也是正常的。是不是可以不要这个文件呢？

**Comment by Efaker** [comment]
构建的gradle文件最好不要随意发挥，容易变了形

**Comment by chriszhao001** [comment]
配置文件是类似这样的，其实就是希望能通过配置自动出多渠道包
    flavorDimensions "channel"
    productFlavors
    {
        AAA01 {
            buildConfigField "String", "CHANNEL", "\"AAA01\""
            applicationIdSuffix '.fdc.m999'
            dimension "channel"
        }
        public_noAD {
            buildConfigField "String", "CHANNEL", "\"public_noAD\""
            dimension "channel"
        }
    }
我现在验证基本上删除了public.xml以后没有什么问题，或者是因为我其实并没有修改什么资源的原因么？

**Comment by Efaker** [comment]
应该是你的资源文件没有被调用到，常规App不配置这个，如果资源文件被调用到的话会崩溃找不到资源文件

**Comment by chriszhao001** [comment]
嗯，了解了，兄弟加油。
