### ISSUE TITLE
Support patch code like DexPatcher?

### ISSUE THREAD

**Issue by camlhsegu** [Efaker/FakerAndroid#12]
Hi, thank you for a awesome project. Can you provide the ability to patch code like DexPatcher?

**Comment by Efaker** [comment]
You can install your own dex by this runtime c++ api `bool installDex(JNIEnv* env, jobject mContext, string dexPath);`  But you should make sure there is no conflict classes with the build in  , I think most time original javacall & original class replacement & smali mod on building time is enough.
