### ISSUE TITLE
abstract 类没有编译出来

### ISSUE THREAD

**Issue by huangwenyan1225** [Efaker/FakerAndroid#13]
abstract 类没有编译出来

**Comment by Efaker** [comment]
jar 是伪代码，影响到你想修改得地方了吗？如果没有影响到得话可以忽略得

**Comment by huangwenyan1225** [comment]
有用到这些类  直接用smai改 语法不是很熟悉    出现情况是伪代码生成类似com.android.bdc$bac 类名   实际上应该是com.android.bdc.bac      导致引用失败

**Comment by Efaker** [comment]
apk 发一下

**Comment by Efaker** [comment]
加我QQ
