### ISSUE TITLE
无法新增layout布局

### ISSUE THREAD

**Issue by liaowangdezhuzhu** [Efaker/FakerAndroid#15]
大佬您好，我尝试去给反编译后的app添加layout但是提示如下，我尝试两个app都是如此，未添加layout和删除layout即可正常编译，请问大佬是暂时不支持layout的添加吗？
![ddddddddd](https://user-images.githubusercontent.com/16397637/102629196-c8305a80-4185-11eb-9aa4-56336ef1beb1.png)

**Comment by Efaker** [comment]
已经修复了
