### ISSUE TITLE
Javascaffoding?

### ISSUE THREAD

**Issue by c0nd3v** [Efaker/FakerAndroid#2]
借助javaScaffoding 使用java代码对smali 类继承
在javaScaffoding模块创建伪类,保持伪类类签名与要继承的类的smali文件路径名称对应->AndroidStudio右侧 Gradle->javaScaffoding->build->build,在主模块（app/src/main/java）中编写自己的类对伪类进行继承
在主模块（app/src/main/java）编写自己的类，类签名与要替换的类的smali文件路径名称对应

I dont understand. Can you give an example?

**Comment by Efaker** [comment]
If you want extends or use a original class but it is a smali file ,now you can counterfeit a class name it same as the smali class  in the javascaffoding moudle then you can write java code  entends or use the class by call the class you defined in java scaffoding moudle to pass the compiler !

Im making the best use of one's time for the prouct itself. when i think it  works well!
I'll offer all kinds  of simples for it !

**Comment by c0nd3v** [comment]
Do you have discord? Please add me ConnorZ#8173
I don't have QQ :(

**Comment by Efaker** [comment]
Sorry for being a chinese!
I dont have discord!
You can write a simple apk for me to download ! I'll give you a respose as quickly  as possible！
For Quick understanding it would be best write it your self!

**Comment by c0nd3v** [comment]
Dont be sorry, I love Chinese. Thank you for your help I will try again myself first

**Comment by Efaker** [comment]
Good luck!

**Comment by c0nd3v** [comment]
My apk is a bit different, the untouched AndroidManifest.xml looks like this:
https://i.imgur.com/e9VkyEl.png

<application> DOES NOT HAVE android:name="XXX" !!

**Comment by c0nd3v** [comment]
I need to inherit com.nianticproject.holoholo.libholoholo.unity.UnityMainActivity

**Comment by c0nd3v** [comment]
https://i.imgur.com/S6BK0ij.png
apk uses default application

**Comment by Efaker** [comment]
https://github.com/Efaker/FakerAndroid-Demos/releases/tag/myJava
Downalod the zip then copy the sub files to your root project!

AndroidStudio Right Gradle->javaScaffoding->build->build

**Comment by c0nd3v** [comment]
Wow thanks!

**Comment by c0nd3v** [comment]
https://i.imgur.com/CzNHGye.png
I dont have this

**Comment by c0nd3v** [comment]
https://i.imgur.com/QdruYZY.png
Cannot use com.nianticproject.holoholo.libholoholo.unity.UnityMainActivity in app

**Comment by c0nd3v** [comment]
Do you have skype?

**Comment by Efaker** [comment]
You can get the new FakerAndroid.jar and have a try just with run the project!

**Comment by Efaker** [comment]
New version need donothing by yourself! Just call the api in the jar!
