### ISSUE TITLE
javaScaffoding 问题

### ISSUE THREAD

**Issue by LuckyLi706** [Efaker/FakerAndroid#22]
我修改了smail代码，把private变成了public，但是javaScaffoding没生成新的jar包，导致private方法一直没法调用，是否有gradle脚本能直接生成jar

**Comment by Efaker** [comment]
先运行一下，然后看看jar包有没有更新，然后gradle文件需要刷新一下

**Comment by LuckyLi706** [comment]
> 先运行一下，然后看看jar包有没有更新，然后build.gradle文件需要刷新一下

非常感谢你的回复，我试了一下还是不行。我用的mac电脑，我想问一下，你这边是如何更新jar包的。

**Comment by Efaker** [comment]
jar文件更新了吗

**Comment by LuckyLi706** [comment]
> jar文件更新了吗

非常感谢，用你最新的jar文件可以了，我看了一下，在点击build的时候多了个smali2dexRelease的task，我想问下，这个task具体是怎么插入的，我看gradle文件里面也没有插入具体的task，非常感谢

**Comment by Efaker** [comment]
这个task是隔空穿墙法加入的，不然没法那么多人称大佬了

**Comment by LuckyLi706** [comment]
哈哈哈，多谢大佬～

**Comment by Layne2016** [comment]
> > jar文件更新了吗
> 
> 非常感谢，用你最新的jar文件可以了，我看了一下，在点击build的时候多了个smali2dexRelease的task，我想问下，这个task具体是怎么插入的，我看gradle文件里面也没有插入具体的task，非常感谢

大佬，这个JAR是怎么更新的，求教

**Comment by LuckyLi706** [comment]
> > > jar文件更新了吗
> > 
> > 
> > 非常感谢，用你最新的jar文件可以了，我看了一下，在点击build的时候多了个smali2dexRelease的task，我想问下，这个task具体是怎么插入的，我看gradle文件里面也没有插入具体的task，非常感谢
> 
> 大佬，这个JAR是怎么更新的，求教

就是上面的那个说的那个gradle task呀。

**Comment by Humenger** [comment]
并没有看到这个smali2dexRelease，请问你们是在哪找到的？
![image](https://user-images.githubusercontent.com/27600008/122539700-74ca9680-d05a-11eb-8c1e-29340bd358a2.png)

**Comment by LuckyLi706** [comment]
> 并没有看到这个smali2dexRelease，请问你们是在哪找到的？
> ![image](https://user-images.githubusercontent.com/27600008/122539700-74ca9680-d05a-11eb-8c1e-29340bd358a2.png)

![微信截图_20210619183920](https://user-images.githubusercontent.com/19245690/122639668-bb3cf580-d12d-11eb-88bb-d5c09ba343f7.png)

**Comment by LuckyLi706** [comment]
> 并没有看到这个smali2dexRelease，请问你们是在哪找到的？
> ![image](https://user-images.githubusercontent.com/27600008/122539700-74ca9680-d05a-11eb-8c1e-29340bd358a2.png)

![Uploading 微信截图_20210619183920.png…]()

**Comment by Humenger** [comment]
我这咋没有？？
![image](https://user-images.githubusercontent.com/27600008/122696055-b20a7080-d274-11eb-8002-2403530e76c3.png)
