### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by liaowangdezhuzhu** [Efaker/FakerAndroid#23]
在解包某个游戏时遇到的
![111](https://user-images.githubusercontent.com/16397637/114960171-171ea000-9e99-11eb-8502-14cddcb730ff.png)

**Comment by Efaker** [comment]
删除一下报错的字符

**Comment by liaowangdezhuzhu** [comment]
感谢 目前来看是没问题了

> 删除一下报错的字符
