### ISSUE TITLE
另一个无法编译问题

### ISSUE THREAD

**Issue by liaowangdezhuzhu** [Efaker/FakerAndroid#24]
虽然Il2cppScaffolding生成了
![image](https://user-images.githubusercontent.com/16397637/115119977-9e752c00-9fdd-11eb-9906-dfbc343ecb25.png)
![image](https://user-images.githubusercontent.com/16397637/115120381-c4033500-9fdf-11eb-9c98-6cd82ab101f2.png)
![image](https://user-images.githubusercontent.com/16397637/115120384-c82f5280-9fdf-11eb-96f5-077c41e8966f.png)

显示x86缺少il2cpp-init.h，我尝试不导入x86的库以及从其他项目拷入缺失的文件最终会显示 缺少<csting>这个库，请问大佬这个该如何解决呢

**Comment by Efaker** [comment]
加qq给一下包

**Comment by liaowangdezhuzhu** [comment]
> 加qq给一下包
已经加了 麻烦通过一下

**Comment by formatingxie** [comment]
In file included from G:\project\A_newProject\StackRider_v1.30\app\src\main\cpp\native-lib.cpp:12:
In file included from G:\project\A_newProject\StackRider_v1.30\app\src\main\cpp\Il2cpp-Scaffolding-ARM64\il2cpp-appdata.h:22:
G:\project\A_newProject\StackRider_v1.30\app\src\main\cpp\Il2cpp-Scaffolding-ARM64\il2cpp-functions.h:43800:57: error: unexpected type name 'MethodInfo': expected expression

**Comment by Efaker** [comment]
删除删除，有些结构里面有不合法名称
