### ISSUE TITLE
android_id

### ISSUE THREAD

**Issue by w1-cell** [Efaker/FakerAndroid#24]
Faker 调用了 android_id 莫？

**Comment by 4163879010** [comment]
我也发现了这问题。将    static {System.loadLibrary("native-lib");}放到splashactivity里加载，然后再splashactivity里的oncreate里fakeApp(application);，而fakeDex(base);注释掉。这样或许可以，但不知道有没有其他问题

**Comment by Efaker** [comment]
update new version fakerandroid
