### ISSUE TITLE
res 混淆重命名问题

### ISSUE THREAD

**Issue by nuoxiang** [Efaker/FakerAndroid#25]
一些 app 对资源进行混淆处理，反编译后生成的文件名可能是 java 关键字，如 do.xml ，if.xml，对应引用处为 R.id.do，R.id.if
建议对该类文件进行重命名，改为 do1.xml 之类

在我手动修复，直接能安装运行，工具很棒！

**Comment by HxBreak** [comment]
fixed commit main:2f8e616427b355ced12263c135370adcfbcc9c06
