### ISSUE TITLE
R$styleable问题

### ISSUE THREAD

**Issue by LuckyLi706** [Efaker/FakerAndroid#26]
一开始反编译没问题。但是我引入了谷歌的广告库就报错了。
implementation (com.google.android.gms:play-services-ads:20.0.0'

报错内容：
Caused by: java.lang.NoSuchFieldError: No static field WaveSideBar of type [I in class Lcom/YiGeTechnology/WeBusiness/R$styleable; or its superclasses (declaration of 'com.YiGeTechnology.WeBusiness.R$styleable' appears in /data/app/com.lucky.yxapp-1cUzTYKDmXFopquyTo_qSA==/base.apk!classes2.dex)

我比较了一下之前和之后的apk，发现R$sytleable变化了
没加这个依赖：
<img width="373" alt="之前的" src="https://user-images.githubusercontent.com/19245690/115953215-bb998580-a51c-11eb-91b1-f61b04e83c85.png">
加了这个依赖：
<img width="396" alt="之后的" src="https://user-images.githubusercontent.com/19245690/115953226-c81dde00-a51c-11eb-8d47-c020d323a239.png">

发现包里面的很多自定义样式都没了。这到底是咋回事？求教。

**Comment by Efaker** [comment]
看一下是不是原包 和 你导入的包有冲突？如果有的话需要把原包的剔除以后再来引入

**Comment by LuckyLi706** [comment]
引入的包也有样式，把smail里面的样式给全部替换了了，而没有叠加在一起。

**Comment by Efaker** [comment]
你得删资源吧？

**Comment by LuckyLi706** [comment]
并不是冲突，引入包的样式和我smail代码里面的样式并不一样。库冲突，我之前做处理了。

**Comment by Efaker** [comment]
加QQ安装包发一下!

**Comment by LuckyLi706** [comment]
之前发你了，你没理我。。我这边修复了，我把主文件的attrs.xml和smail代码里面的R$styleable.smail手动合并到主文件的attrs.xml里面去了，然后就没问题了。不知道是不是是不是依赖的资源文件的优先级更高导致的。

**Comment by Efaker** [comment]
不好意思，忙没来得及处理

**Comment by LuckyLi706** [comment]
没事，后期你看看是否这是个问题。如果是可以考虑修复下。
