### ISSUE TITLE
修改Text_set_text后闪退

### ISSUE THREAD

**Issue by formatingxie** [Efaker/FakerAndroid#27]
void HookedText_set_text(Text * __this, String * value, MethodInfo * method){
    const char *t = coverIl2cppString2Char(reinterpret_cast<Il2CppString *>(value));
    LOGI("xxxxclass %s---- HookedText_set_text",t); //先用这行日志分析捕捉一下文字
    if(strcmp(t,"140")==0){
        Text_set_text(__this, value,method);
        MonoString *ms = coverChar2Il2cppString("100000");
        Text_set_text(__this, reinterpret_cast<String *>(ms), method);
        return;
    }

    Text_set_text(__this, value,method);
}

extern "C"
JNIEXPORT void JNICALL
Java_com_faker_android_FakerApp_fakeApp(JNIEnv *env, jobject thiz, jobject application) {
    fakeApp(env,application);

    /**
     * you can do yor hook work here
     * below  is demo code demo code hook libil2cpp.so
     */
    long base = baseImageAddr("libil2cpp.so");
    LOGE("baseIamgeAddr : %ld",base);
    init_il2cpp(base);
    //fakeCpp((void *) Behaviour_get_isActiveAndEnabled, (void *)HookedBehaviour_get_isActiveAndEnabled ,reinterpret_cast<void **>(&Behaviour_get_isActiveAndEnabled));
    fakeCpp((void *) Text_set_text, (void *)HookedText_set_text ,reinterpret_cast<void **>(&Text_set_text));
}

**Comment by Efaker** [comment]
兄弟，这个问题不好解释啊，你操作的姿势和我demo中一样吗

**Comment by formatingxie** [comment]
大佬 是一样的啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月27日(星期二) 下午5:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Efaker/FakerAndroid] 修改Text_set_text后闪退 (#27)





 
兄弟，这个问题不好解释啊，你操作的姿势和我demo中一样吗

**Comment by formatingxie** [comment]
![image](https://user-images.githubusercontent.com/4608093/116492554-1b05e580-a8cf-11eb-8b8e-4abd1754a233.png)
大佬 调用Text_set_text后 设置显示成功了 然后就闪退了

**Comment by HxBreak** [comment]
你这个是不是没做空指针判断

**Comment by formatingxie** [comment]
做了空指针判断 也都打印了 不是空指针

**Comment by HxBreak** [comment]
你试试看hook其他方法正常不正常，如果正常可能是hook框架的问题

**Comment by formatingxie** [comment]
好 我试试  谢谢大佬

**Comment by formatingxie** [comment]
![image](https://user-images.githubusercontent.com/4608093/117436776-f3afb800-af61-11eb-9f32-cd113850722f.png)
大佬 这个修改了文本会乱码，用的你的demo 其他地方都没动
