### ISSUE TITLE
AS3.5.3安装插件之后打开apk报错

### ISSUE THREAD

**Issue by tpnet** [Efaker/FakerAndroid#28]
环境:mac os 11.3，已安装.Net5.0
报错如下：
![image](https://user-images.githubusercontent.com/17380722/118346061-6aa10e00-b56b-11eb-9ca4-dfa15b421195.png)

**Comment by Efaker** [comment]
能升级到 4.1吗？或者如果着急先使用FakerAndroid.jar

**Comment by tpnet** [comment]
@Efaker 使用FakerAndroid.jar导出来的项目也不支持AS3.5.3，必须升级AS4.1吗？？？

**Comment by Efaker** [comment]
最好升级一下吧，目前一直是在高版本上测试的
