### ISSUE TITLE
javaScaffoding问题

### ISSUE THREAD

**Issue by zwq194** [Efaker/FakerAndroid#30]
对类里面的单例模式反编译不对，导致类替换编译报错：
jadx反编译是对的：
public class CheckUtil {

    /* renamed from: a */
    private static final String f18773a = "xxx";

    /* renamed from: b */
    private static final String f18774b = "xxx";

    /* renamed from: d.c.c.g.z$b */
    /* compiled from: CheckUtil */
    private static class C3937b {

        /* renamed from: a */
        private static final CheckUtil f18775a = new CheckUtil();

        private C3937b() {
        }
    }
}
FakerAndroid反编译不对：
public class z {
    private static final String a = "xxx";
    private static final String b = "xxx";

    private z() {
    }

    public static final z f() {
        return z.b.a;
    }
}

**Comment by Efaker** [comment]
兄弟，我没看懂啊

**Comment by Efaker** [comment]
你不要单看jar jar是伪代码，真正参与回编译打包的还是smali，得需要看smali对不对

**Comment by zwq194** [comment]
那我替换类咋搞呢

**Comment by zwq194** [comment]
我是看着你的教程搞的

**Comment by Efaker** [comment]
让你写的代码可以合法被他的smali调用

**Comment by zwq194** [comment]
问题现在的伪代码不对啊

**Comment by zwq194** [comment]
你教程不是拷贝伪代码进行修改的么

**Comment by Efaker** [comment]
是参照，有的为代码逻辑就不对，还是得看具体的s ma li

**Comment by zwq194** [comment]
javaScaffoding下面的class只是个参照作用？要修改还是的修改smali是么

**Comment by zwq194** [comment]
我修改smali之后，debug是可以了，javaScaffoding伪代码也跟着更新了，这个还是的修改smali

**Comment by zwq194** [comment]
done
