### ISSUE TITLE
如何在native-lib.cpp里面调用游戏内的某个方法

### ISSUE THREAD

**Issue by huihuidedashao** [Efaker/FakerAndroid#31]
游戏内视频按钮，已经hooked，下发奖励函数是AdManager_TestReward，怎么调用？
![e3ea9082c3812dde0dc734aa234d325](https://user-images.githubusercontent.com/38172662/191729477-d4d4f632-9830-44bf-ae26-10ec149caf57.png)

![d004977713a4ee642789b3511b71a62](https://user-images.githubusercontent.com/38172662/191729524-bf3d91bc-81f8-4a87-8e56-76f5c4d6ba60.png)

**Comment by zhangtao45614** [comment]
如果接的是MaxSdk，直接去java层的hook，然后直接模拟回调
