### ISSUE TITLE
android studio打开之后无法运行

### ISSUE THREAD

**Issue by afunnyrainman** [Efaker/FakerAndroid#31]
Cause: exception while building Json $Cannot run program "/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake": error=2, No such file or directory
Mac 电脑使用jar包将apk生成成项目之后无法运行。

**Comment by Efaker** [comment]
看你的貌似是ndk环境没有配置的原因奥

**Comment by afunnyrainman** [comment]
哦哦 需要配置ndk嘛？我不知道呢，我配置一下看看。多谢

**Comment by afunnyrainman** [comment]
强呀 哥儿，小白觉得太神了

**Comment by Efaker** [comment]
那你偷偷的去美吧
