### ISSUE TITLE
引入第三方库出现编译错误，正确的姿势是什么

### ISSUE THREAD

**Issue by zwq194** [Efaker/FakerAndroid#32]
引入第三方库，build报错，想问一下大神，可以引入第三方库吗
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.RuntimeException: 
  Add the plugin to your project build script :
  buildscript {
      repositories {
         mavenCentral()
         google()
      }
      dependencies {
          classpath 'com.xxx.xxx:plugin:{version}'
          ...
      }
  }

**Comment by Efaker** [comment]
可以啊，第三方依赖是在app 目录下的 build.gradle文件

**Comment by zwq194** [comment]
> 可以啊，第三方依赖是在app 目录下的 build.gradle文件

是在app 目录下的 build.gradle文件引入的，build报错啊

**Comment by zwq194** [comment]
> 可以啊，第三方依赖是在app 目录下的 build.gradle文件

我新建安卓项目，引入第三方库，build没有问题

**Comment by Efaker** [comment]
QQ我

**Comment by zwq194** [comment]
大佬真屌，已经解决

**Comment by zwq194** [comment]
done
