### ISSUE TITLE
AndroidStudio编译工程报错 Error: do is not a valid resource name (reserved Java keyword)

### ISSUE THREAD

**Issue by jianweizhou** [Efaker/FakerAndroid#33]
Error: do is not a valid resource name (reserved Java keyword)

**Comment by jianweizhou** [comment]
Error: if is not a valid resource name (reserved Java keyword)

**Comment by jianweizhou** [comment]
文件名 和 资源id 都会报错。

**Comment by Efaker** [comment]
你的资源文件做过混淆了，需要人工修正，是否可以成功看你运气了
