### ISSUE TITLE
hook方法之后，如何调用原方法？

### ISSUE THREAD

**Issue by ccWuu** [Efaker/FakerAndroid#34]
1.fakeCpp((void *)Behaviour_get_isActiveAndEnabled, (void *)HookedBehaviour_get_isActiveAndEnabled, reinterpret_cast<void **>(&Behaviour_get_isActiveAndEnabled));
2.HookedBehaviour_get_isActiveAndEnabled中调用callJava方法。
3.java层处理完毕，想调用原方法Behaviour_get_isActiveAndEnabled
请问大神应该怎么弄啊？每次都是null pointer dereference。

**Comment by Efaker** [comment]
使用java层的 UnitySendMessage ，目前没有好的办法在没有原函数配参的情况下调用原函数
