### ISSUE TITLE
error: unexpected type name 'MethodInfo': expected expression

### ISSUE THREAD

**Issue by formatingxie** [Efaker/FakerAndroid#37]
In file included from G:\project\StackRider_v1.30\app\src\main\cpp\native-lib.cpp:12:
In file included from G:\project\StackRider_v1.30\app\src\main\cpp\Il2cpp-Scaffolding-ARM64\il2cpp-appdata.h:22:
G:\project\StackRider_v1.30\app\src\main\cpp\Il2cpp-Scaffolding-ARM64\il2cpp-functions.h:43801:57: error: unexpected type name 'MethodInfo': expected expression

更新了最新的fakerandroid.jar 也报这个 大佬可以加下你qq么

**Comment by Efaker** [comment]
删除删除，注释注释，报错的结构体

**Comment by formatingxie** [comment]
可能是包加密引起的，
