### ISSUE TITLE
Android Project Generate without error but can not run

### ISSUE THREAD

**Issue by codingwatching** [Efaker/FakerAndroid#44]
Hi @Efaker I have this error when trying to run android project:

Execution failed for task ':app:generateJsonModelDebug'.
> executing external native build for cmake /Users/project/app/src/main/cpp/CMakeLists.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Here is the CMakeLists.txt file content
```
#Generated by FakerAndroid for doc or help by https://github.com/Efaker/FakerAndroid

add_definitions(-DENABLE_DEBUG -DABC)
cmake_minimum_required(VERSION 3.6)
include_directories(src/main/cpp/include)

find_package(base REQUIRED CONFIG)

file(GLOB native_srcc "${CMAKE_SOURCE_DIR}/*.cpp")
add_library(
        native-lib
        SHARED
        ${native_srcc}
        )
target_link_libraries(
        native-lib
        base::tool
        android
        z
        log)
```
Please help, Thank you so much!

**Comment by Efaker** [comment]
can give erro screenshot

**Comment by codingwatching** [comment]
Hi @Efaker 
The root cause is the .DS_Store file
prefabException in thread "main" java.io.FileNotFoundException: /.gradle/caches/transforms-2/files-2.1/c196ab56181acf6c7f26ac34fdf6e991/support-1.0.31/prefab/modules/.DS_Store/module.json (Not a directory)
So I just delete the .DS_Store and the project now can build!
Thank you so much!
