### ISSUE TITLE
【求大神指点】AS打开run工程一直转圈，还有报错

### ISSUE THREAD

**Issue by lswd** [Efaker/FakerAndroid#45]
![图片](https://user-images.githubusercontent.com/24218775/122752080-181de480-d2c3-11eb-9df4-415d04710fa3.png)
![图片](https://user-images.githubusercontent.com/24218775/122752323-64692480-d2c3-11eb-9947-d74745962ae9.png)
哪位大神帮忙看下，执行命令之后AS打开工程Run运行，一直转圈，时间很长很长，并且有报错，对NDK的不了解，希望大神指点下如何处理

**Comment by Efaker** [comment]
把特殊字符删除删除

**Comment by lswd** [comment]
感谢大神指点

**Comment by lswd** [comment]
> 把特殊字符删除删除



> 把特殊字符删除删除

感谢大神
