### ISSUE TITLE
请教: error: **redefinition of 'Il2CppClass' as different kind of symbol** 无法编译通过

### ISSUE THREAD

**Issue by wzpyh** [Efaker/FakerAndroid#49]
In file included from C:\Work\FakeAndroid\game\app\src\main\cpp\native-lib.cpp:15:
In file included from C:\Work\FakeAndroid\game\app\src\main\cpp\Il2cpp-Scaffolding-ARM\il2cpp-appdata.h:6:
C:\Work\FakeAndroid\game\app\src\main\cpp\Il2cpp-Scaffolding-ARM\il2cpp-types.h:1900:3: error: **redefinition of 'Il2CppClass' as different kind of symbol**

请教一下怎么解决才好。。
游戏: https://apkcombo.com/apk-downloader/?q=com.fannagame.xyqyfs.xm

**Comment by Efaker** [comment]
把报错的某些字符删除删除

**Comment by wzpyh** [comment]
替换了一下字符果然可以了，谢谢
