### ISSUE TITLE
needed by armeabi-v7a/libnative-lib.so

### ISSUE THREAD

**Issue by oogie56** [Efaker/FakerAndroid#5]
run后遇到如下报错：

Error while executing process ~/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build ~/xxx/xxx/com.aa.bb/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target native-lib}

ninja: error: '../../../../src/main/jniLibs/armeabi-v7a/libswap.so', needed by '~/xxx/xx/com.aa.bb/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libnative-lib.so', missing and no known rule to make it

使用命令生成项目后没做修改即运行，生成的项目目录下的jniLibs下只有一个arm64-v8a

CMakeLists.txt的配置 ../../../../src/main/jniLibs/${ANDROID_ABI} 把ANDROID_ABI识别成armeabi-v7a，这是什么原因呢

**Comment by Efaker** [comment]
暂时对库兼容的不好，你手动改一下build文件

**Comment by Efaker** [comment]
新版本已經修復
