### ISSUE TITLE
部分app出现了同名的so文件，无法编译通过->native-lib

### ISSUE THREAD

**Issue by cliangtime** [Efaker/FakerAndroid#51]
如题，报错信息如下
`More than one file was found with OS independent path 'lib/armeabi-v7a/libnative-lib.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
`

**Comment by Efaker** [comment]
那你把自己的改一下子名字就好啊
