### ISSUE TITLE
About android:name="android.permission.READ_PHONE_STATE permission

### ISSUE THREAD

**Issue by nianhua-suiyue** [Efaker/FakerAndroid#58]
Use android studio to create a new empty project After adding android.permission.READ_PHONE_STATE permission permission in AndroidManifest.xml, the fake project starts, and in vivo version 7.12, you will be prompted to request permission

**Comment by nianhua-suiyue** [comment]
onJniLoad(vm,reserved); If this statement is commented out, there is no request

**Comment by Efaker** [comment]
test case in improve

**Comment by Efaker** [comment]
new verion close
