### ISSUE TITLE
google play 上传aab格式，下载下来的包调用fakeCpp会报空指针

### ISSUE THREAD

**Issue by CChilde** [Efaker/FakerAndroid#59]
最新的google play包需要上传aab格式了，aab最终会转换成xapk下载下来，这种 apks 的格式会将lib下面的所有 .so 文件单独打包成一个 apk，而不在原来的 apk 里面，所以 baseImageAddr("libil2cpp.so") 会因为找不到 libil2cpp.so 这个库返回 0，所以调用 fakeCpp 会找不到正确的地址而闪退，麻烦大大看看能否处理这个问题，本地能通过 bundletool 这个工具将 aab 转换成 apks 并安装（另外再插一句和这个问题无关的话，关于文本转换的，通过 const char* 转换成 String*，如果是中文的话，基本会闪退，如果是通过 Text_set_Text 这个方法调用的话，闪退的概率没这么大，但是频繁调用最终也会闪退）

**Comment by Efaker** [comment]
unzip then zip the files to a apk then use fakerandroid you get the common apk

**Comment by CChilde** [comment]
大大能否公开下 baseImageAddr("libil2cpp.so") 这个方法的源码。感谢大大解答

**Comment by liang530** [comment]
@CChilde 替换文本闪退的问题有找到解决方案吗？
