### ISSUE TITLE
I try the hook function but nothing happens.

### ISSUE THREAD

**Issue by geokar2006** [Efaker/FakerAndroid#6]
I try the hook function but nothing happens. Behaviour_get_isActiveAndEnabled works fine.
The function I'm trying to hook is update in the first Person Control class.
What can I do to fix this?

**Comment by Efaker** [comment]
does your replace_call method  work? You should log more in you replace_call method to change the  some thing you want

**Comment by geokar2006** [comment]
> does your replace_call method work? You should log more in you replace_call method to change the some thing you want

At the very beginning of replace_call I added log, but it is not displayed.

**Comment by Efaker** [comment]
Can you offer your apk orignal!

**Comment by Efaker** [comment]
In your dev environment did you try the demo i offered!

**Comment by geokar2006** [comment]
> Can you offer your apk orignal!

https://apkcombo.com/apk-downloader/?device=&arches=&sdkInt=&sa=1&lang=en&dpi=480&q=com.aleson.casefiveanimatronicsfnaf

**Comment by Efaker** [comment]
I will give you a respose later but not today ! you can try the demo i offered first!

**Comment by geokar2006** [comment]
> I will give you a respose later but not today ! you can try the demo i offered first!

I tried it. The demo works.

**Comment by geokar2006** [comment]
> I will give you a respose later but not today ! you can try the demo i offered first!



> > I will give you a respose later but not today ! you can try the demo i offered first!
> 
> I tried it. The demo works.

but all functions except Behaviour_get_isActiveAndEnabled do not output log

**Comment by geokar2006** [comment]
> > I will give you a respose later but not today ! you can try the demo i offered first!
> 
> > > I will give you a respose later but not today ! you can try the demo i offered first!
> > 
> > 
> > I tried it. The demo works.
> 
> but all functions except Behaviour_get_isActiveAndEnabled do not output log

I can give proof of this.

**Comment by geokar2006** [comment]
> > > I will give you a respose later but not today ! you can try the demo i offered first!
> > 
> > 
> > I tried it. The demo works.
> 
> but all functions except Behaviour_get_isActiveAndEnabled do not output log

**Comment by geokar2006** [comment]
I tried a few more options. All methods except Behaviour_get_isActiveAndEnabled do not hook.

**Comment by Efaker** [comment]
Sorry I found no idea

**Comment by geokar2006** [comment]
> Sorry I found no idea

Maybe not dobby hook is the best idea?

**Comment by Efaker** [comment]
Have you try other apks? Maybe there is someting wrony with the il2cpp scfaffoding

**Comment by geokar2006** [comment]
> Have you try other apks? Maybe there is someting wrony with the il2cpp scfaffoding

I tried your demo. It also worked only Behaviour_get_isActiveAndEnabled

**Comment by Efaker** [comment]
Behaviour_get_isActiveAndEnabled is just a demo ,It is not a standard api for all games i think, I type this just want explain how to hook il2cpp method,You should do your work by your current case!

**Comment by Efaker** [comment]
I think i should close the issue now,your title is so broad sense but your case is special  and this can effect other's definition
