### ISSUE TITLE
自定义属性怎么处理呢

### ISSUE THREAD

**Issue by YandZD** [Efaker/FakerAndroid#7]
main\res\layout\a0.xml:2: error: attribute paddingBottomNoButtons (aka com.tencent.news:paddingBottomNoButtons) not found.
main\res\layout\a0.xml:2: error: attribute paddingTopNoTitle (aka com.tencent.news:paddingTopNoTitle) not found.
main\res\layout\a02.xml:9: error: attribute defaultImageScaleType (aka com.tencent.news:defaultImageScaleType) not found.
main\res\layout\a02.xml:9: error: attribute riv_corner_radius (aka com.tencent.news:riv_corner_radius) not found.
main\res\layout\a02.xml:9: error: attribute riv_corner_radius_which (aka com.tencent.news:riv_corner_radius_which) not found.
main\res\layout\a02.xml:9: error: attribute viewAspectRatio (aka com.tencent.news:viewAspectRatio) not found.
main\res\layout\a02.xml:10: error: attribute defaultImageScaleType (aka com.tencent.news:defaultImageScaleType) not found.
main\res\layout\a02.xml:10: error: attribute viewAspectRatio (aka com.tencent.news:viewAspectRatio) not found.
main\res\layout\a02.xml:11: error: attribute defaultImageScaleType (aka com.tencent.news:defaultImageScaleType) not found.
main\res\layout\a02.xml:11: error: attribute riv_corner_radius (aka com.tencent.news:riv_corner_radius) not found.
main\res\layout\a02.xml:11: error: attribute riv_corner_radius_which (aka com.tencent.news:riv_corner_radius_which) not found.
main\res\layout\a02.xml:11: error: attribute viewAspectRatio (aka com.tencent.news:viewAspectRatio) not found.
main\res\layout\a03.xml:8: error: attribute defaultImageScaleType (aka com.tencent.news:defaultImageScaleType) not found.
main\res\layout\a03.xml:8: error: attribute placeholder (aka com.tencent.news:placeholder) not found.
main\res\layout\a03.xml:8: error: attribute riv_corner_radius (aka com.tencent.news:riv_corner_radius) not found.
main\res\layout\a03.xml:8: error: attribute riv_corner_radius_which (aka com.tencent.news:riv_corner_radius_which) not found.
main\res\layout\a03.xml:8: error: attribute viewAspectRatio (aka com.tencent.news:viewAspectRatio) not found.
main\res\layout\a03.xml:9: error: attribute defaultImageScaleType (aka com.tencent.news:defaultImageScaleType) not found.
main\res\layout\a03.xml:9: error: attribute placeholder (aka com.tencent.news:placeholder) not found.
main\res\layout\a03.xml:9: error: attribute viewAspectRatio (aka com.tencent.news:viewAspectRatio) not found.

**Comment by Efaker** [comment]
哥，这个不是自定义属性，是混淆导致的， 删减删减

**Comment by YandZD** [comment]
好的，解决了。根据 public.xml、R$attr.smali 还原一份attrs.xml，再合并到原版attrs.xml。

**Comment by Efaker** [comment]
> 好的，解决了。根据 public.xml、R$attr.smali 还原一份attrs.xml，再合并到原版attrs.xml。

好尼玛牛逼类忒，回头分享一下哦

**Comment by YandZD** [comment]
[MyApplication.zip](https://github.com/Efaker/FakerAndroid/files/5568739/MyApplication.zip)
替换assets下的文件，生成的attrs.xml合并到破解的app原来的attrs.xml。
