### ISSUE TITLE
貌似插件里面的工具链写死了

### ISSUE THREAD

**Issue by lovely3x** [Efaker/FakerAndroid#8]
:app:externalNativeBuildDebug
C:/Users/Yang/AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/ostream
undefined reference to 'std::__ndk1::ios_base::getloc() const'

**Comment by Efaker** [comment]
暂时不要用这个abi吧，没有测试过 x86_64

**Comment by Efaker** [comment]
已经修复了，试试新版本如果再有问题的话加一下我的QQ谢了
