### ISSUE TITLE
coverChar2Il2cppString 后面几个字符乱码。显示为【完美敒瑣】

### ISSUE THREAD

**Issue by 644368912** [Efaker/FakerAndroid#9]
初步判断应该是没有字符串结束符【\0】但是加上结束符。问题依旧
请问下作者你有什么解决办法吗？    
if(strcmp(t,"不法世界")==0){//这个不法世界感觉是个敏感词，发布渠道的话过审有问题，所以修改一下
        Text_set_text(__this, value,method);
        MonoString *ms = coverChar2Il2cppString("完美世界");
        Text_set_text(__this, reinterpret_cast<String *>(ms), method);
        return;
    }

**Comment by HackerGBD** [comment]
字体库的问题吧

**Comment by 644368912** [comment]
> 字体库的问题吧

我传英文也会这样。字体库我已经替换成中文的了。你不会这样吗？难道是我的环境问题？

**Comment by HackerGBD** [comment]
> 

String * hook_Text_get_text(Text * __this){
    String * res = Text_get_text(__this,NULL);
    const char *s = coverIl2cppString2Char(reinterpret_cast<Il2CppString *>(res));
    //UNLOCK RANDOM
    if(strcmp(s,"UNLOCK RANDOM")==0){
        const char* ch = "随机解锁";
        res =  (String*)il2cpp_string_new(ch);
    }
    return res;
}
我这样写 没毛病

**Comment by tigericon** [comment]
你好，我使用hook_Text_get_text 之后就会闪退 又碰到这样的情况吗？ 

> > 
> 
> String * hook_Text_get_text(Text * __this){ String * res = Text_get_text(__this,NULL); const char _s = coverIl2cppString2Char(reinterpret_cast<Il2CppString _>(res)); //UNLOCK RANDOM if(strcmp(s,"UNLOCK RANDOM")==0){ const char_ ch = "随机解锁"; res = (字符串_)il2cpp_string_new(ch); } 返回资源； } 我这样写没毛病
